uv run --project pyprojects/minimal -m src_py.modal.launch_modal_orchestration \
    --model-cli-name qwen25 \
    --config-nickname grpo_notool_2400 \
    --use-tool false \
    --training-rollout-config-path config/rollout_config_training_grpo_notool.json \
    --num-total-epochs 1 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 3 \
    --training-config-common-path config/training/common_lora.toml \
    --training-time 2400 \
    --training-rollout-time-limit-secs 2400 \
    --validation-rollout-time-limit-secs 1200 \
    --num-gpus 1 \
    --gpu-name H200 \
    --mount-dir "/volume" \
    --positive-advantage-only false \
    --keep-action-logs true \
