model_cli_name = "qwen25"
config_nickname = "tree_notool_lora_r32_lr1e6_semionline"
use_tool = false
training_rollout_config_path = "config/rollout_config_training_tree.json"
num_total_epochs = 7
num_iterations_limit = 3
training_rollout_secs = 2100
validation_rollout_secs = 3600
training_time = 9000.0
num_gpus = 1
inference_backend = "vllm"
training_trajectory_len_cutoff = 4096
total_time_limit_hours = 10.0
mount_dir = "/work/hdd/bhph/zluo8/credit_assignment/results"
keep_action_logs = false
positive_advantage_only = false
training_set_sort_mode = "ByQuestion"
force_selected_branch_token = true
judgment_cache_config_nickname = "tree_notool_forced_patched_rollout_30chunk"
training_questions_per_epoch = 1250

[training_hyperparameters]
lora_or_full = "lora"
distributed_strategy = "single_gpu"
advantage_clip = 3.0
kl_beta = 0.0
learning_rate = 1e-06
weight_decay = 0.01
use_adam_state = true
use_lr_warmup = true
min_grad_accum_steps = 16
max_batch_tokens = 0
log_time_interval = 30
seed = 42
adam_beta1 = 0.9
adam_beta2 = 0.95
lr_warmup_steps = 100
lora_rank = 32
lora_alpha = 64
lora_dropout = 0.05
lora_save_mode = "adapter"
