[project]
name = "credit-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "datasets>=4.8.5",
    "dotenv>=0.9.9",
    "grpcio>=1.74.0",
    "grpcio-tools>=1.74.0",
    "research-utility",
    "torch",
    # "transformers",
    "transformers",
    "sglang==0.5.10",
    # used for LLM python tool calling
    "sympy>=1.14.0",
    "numpy>=2.4.6",
    "scipy>=1.17.1",
    "numexpr>=2.14.1",
    "matplotlib>=3.10.9",
    "peft>=0.19.1",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
research-utility = { path = "../research-utility", editable = true }

[tool.uv]
environments = ["sys_platform == 'linux'"]
prerelease = "allow"
