model_cli_name = "qwen25"
config_nickname_rollout = "grpo_notool_rollout"
config_nickname_generation = "grpo_notool_generation_by_question"
rollout_config_path = "config/rollout_config_training_grpo.json"
use_tool = false
epoch = 0
training_advantage_policy = "GrpoTerminalReward"
positive_advantage_only = false
rollout_mount_dir = "/work/nvme/bhph/zluo8/credit_assignment/results"
generation_mount_dir = "/work/hdd/bhph/zluo8/credit_assignment/results"
num_gpus = 1
total_time_limit_hours = 1.0
training_set_sort_mode = "ByQuestion"
