model_cli_name = "qwen25"
config_nickname_rollout = "tree_tool_rollout"
config_nickname_generation = "tree_tool_generation"
rollout_config_path = "config/rollout_config_training_tree.json"
use_tool = true
epoch = 0
training_advantage_policy = "TreeMappoPosterior"
positive_advantage_only = false
rollout_mount_dir = "/work/nvme/bhph/zluo8/credit_assignment/results"
generation_mount_dir = "/work/nvme/bhph/zluo8/credit_assignment/results"
num_gpus = 1
total_time_limit_hours = 1.0
training_set_sort_mode = "ByLengthAscending"
