use serde::{Deserialize, Serialize};
use tokenizers::Tokenizer;

use crate::{
    direct_answer::generate_raw_answers::LlmModel, em::em_types::EmHyperparameters,
    em::em_schema::short_hyperparameter_hash,
    parallel_process_jsonl::{read_json, read_json_lines, write_json, write_jsonl_file},
    training_set::training_set_formatted::{AssetFileTrainingFormatted, TrainingSampleFormatted},
    version_tracking::{AssetFile, Base64Hash, hash_file},
};
// The tokenization should follow the following rules:
// 1. The <__*__> tags should be removed before tokenization.
// 2. Only the contents within <__response_start__> and <__response_end__> should have non-null labels. The labels are typically the same as the input_ids.
// 3. However, the contents within <__tool_response_start__> and <__tool_response_end__> should have null labels, as they are not part of the target response to be generated by the model,
// except for the first token after <__tool_response_start__>, whose label should be "end of conversation", to make the model learn to end the response generation when tool calls are made.
// Here is a concrete example:
// Formatted content:
// User: What is 1+1? Assistant: <__response_start__>Let me call the tool. <tool_call>What is 1+1?</tool_call> <__tool_response_start__><tool_response>The answer is 2.</tool_response><__tool_response_end__> Therefore, the answer is 2.<__response_end__>
// Tokenized input_ids (after removing tags, should be in the form of integers in practice):
// ["User:", "What", "is", "1+1?", "Assistant:", "Let", "me", "call", "the", "tool.", "<tool_call>", "What", "is", "1+1?", "</tool_call>", "<tool_response>", "The", "answer", "is", "2.", "</tool_response>", "Therefore,", "the", "answer", "is", "2."]
// Labels:
// [null, null, null, null, null, "Let", "me", "call", "the", "tool.", "<tool_call>", "What", "is", "1+1?", "</tool_call>", <END_OF_CONVERSATION>, null, null, null, null, null, "Therefore,", "the", "answer", "is", "2."]


#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingSampleTokenized {
    pub question_id: usize,
    pub node_id: usize,
    pub input_ids: Vec<i32>,
    pub labels: Vec<i32>,
    pub reconstructed: String,
    pub input_length: usize,
    pub advantage: f64,
}

pub struct AssetFileTrainingTokenized {
    pub model: LlmModel,
    pub dataset: String,
    pub num_samples: usize,
    pub hyperparameters: EmHyperparameters,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetFileTrainingTokenizedTracking {
    pub formatted_hash: Base64Hash,
    pub tokenized_schema_version: usize,
}

impl AssetFileTrainingTokenized {
    const RESPONSE_START_TAG: &'static str = "<__response_start__>";
    const RESPONSE_END_TAG: &'static str = "<__response_end__>";
    const TOOL_RESPONSE_START_TAG: &'static str = "<__tool_response_start__>";
    const TOOL_RESPONSE_END_TAG: &'static str = "<__tool_response_end__>";
    const END_OF_CONVERSATION_TOKEN: &'static str = "<|im_end|>";
    const IGNORE_LABEL: i32 = -100;
    const TOKENIZED_SCHEMA_VERSION: usize = 2;

    pub fn hyperparameter_hash(&self) -> String {
        short_hyperparameter_hash(&self.hyperparameters)
    }

    pub fn file_path(&self) -> String {
        format!(
            "results/{}/agent/{}_training_tokenized_{}_{}.jsonl",
            self.model.cli_name(),
            self.dataset,
            self.num_samples,
            self.hyperparameter_hash(),
        )
    }

    pub fn version_tracking_path(&self) -> String {
        format!(
            "results_version_tracking/{}/agent/{}_training_tokenized_{}_{}.version.json",
            self.model.cli_name(),
            self.dataset,
            self.num_samples,
            self.hyperparameter_hash(),
        )
    }

    fn load_tokenizer(&self) -> Tokenizer {
        assert!(self.model.is_qwen(), "Training tokenization currently supports Qwen models only");
        Tokenizer::from_pretrained(self.model.api_name(), None).unwrap_or_else(|err| {
            panic!(
                "Failed to load tokenizer for model {} from {}: {}",
                self.model.cli_name(),
                self.model.api_name(),
                err
            )
        })
    }

    fn formatted_to_tokenized_with_tokenizer(
        &self,
        formatted_sample: &TrainingSampleFormatted,
        tokenizer: &Tokenizer,
    ) -> TrainingSampleTokenized {
        #[derive(Clone, Copy, PartialEq, Eq)]
        enum ByteMode {
            OutsideResponse,
            InResponse,
            InToolResponse,
        }

        let end_of_conversation_id_u32 = tokenizer
            .token_to_id(Self::END_OF_CONVERSATION_TOKEN)
            .unwrap_or_else(|| {
                panic!(
                    "Tokenizer for model {} must contain {} token",
                    self.model.cli_name(),
                    Self::END_OF_CONVERSATION_TOKEN
                )
            });
        assert!(
            end_of_conversation_id_u32 <= i32::MAX as u32,
            "End-of-conversation token id must fit in i32"
        );
        let end_of_conversation_id = end_of_conversation_id_u32 as i32;

        let original = formatted_sample.content_formatted.as_str();
        let mut cleaned = String::new();
        let mut byte_modes: Vec<ByteMode> = Vec::new();
        let mut cursor = 0usize;
        let mut in_response = false;
        let mut in_tool_response = false;

        let tags = [
            Self::RESPONSE_START_TAG,
            Self::RESPONSE_END_TAG,
            Self::TOOL_RESPONSE_START_TAG,
            Self::TOOL_RESPONSE_END_TAG,
        ];

        while cursor < original.len() {
            let mut next_tag: Option<(usize, &'static str)> = None;
            for tag in tags {
                if let Some(relative_pos) = original[cursor..].find(tag) {
                    let absolute_pos = cursor + relative_pos;
                    match next_tag {
                        Some((existing_pos, _)) if absolute_pos >= existing_pos => {}
                        _ => next_tag = Some((absolute_pos, tag)),
                    }
                }
            }

            let next_text_end = match next_tag {
                Some((pos, _)) => pos,
                None => original.len(),
            };
            if next_text_end > cursor {
                let text_chunk = &original[cursor..next_text_end];
                cleaned.push_str(text_chunk);
                let mode = if in_tool_response {
                    ByteMode::InToolResponse
                } else if in_response {
                    ByteMode::InResponse
                } else {
                    ByteMode::OutsideResponse
                };
                byte_modes.extend(std::iter::repeat_n(mode, text_chunk.len()));
            }

            let Some((tag_pos, tag)) = next_tag else {
                break;
            };
            assert_eq!(tag_pos, next_text_end, "Tag parsing cursor mismatch");

            if tag == Self::RESPONSE_START_TAG {
                assert!(
                    !in_response,
                    "Unexpected nested {} in formatted sample (question_id={}, node_id={})",
                    Self::RESPONSE_START_TAG,
                    formatted_sample.question_id,
                    formatted_sample.node_id
                );
                assert!(
                    !in_tool_response,
                    "Tool response mode must be off at {}",
                    Self::RESPONSE_START_TAG
                );
                in_response = true;
            } else if tag == Self::RESPONSE_END_TAG {
                assert!(
                    in_response,
                    "Missing {} before {} in formatted sample (question_id={}, node_id={})",
                    Self::RESPONSE_START_TAG,
                    Self::RESPONSE_END_TAG,
                    formatted_sample.question_id,
                    formatted_sample.node_id
                );
                assert!(
                    !in_tool_response,
                    "Tool response mode must be off at {}",
                    Self::RESPONSE_END_TAG
                );
                in_response = false;
            } else if tag == Self::TOOL_RESPONSE_START_TAG {
                assert!(
                    in_response,
                    "{} must appear inside response region (question_id={}, node_id={})",
                    Self::TOOL_RESPONSE_START_TAG,
                    formatted_sample.question_id,
                    formatted_sample.node_id
                );
                assert!(
                    !in_tool_response,
                    "Unexpected nested {} in formatted sample (question_id={}, node_id={})",
                    Self::TOOL_RESPONSE_START_TAG,
                    formatted_sample.question_id,
                    formatted_sample.node_id
                );
                in_tool_response = true;
            } else {
                assert_eq!(tag, Self::TOOL_RESPONSE_END_TAG, "Unexpected tag in parser");
                assert!(
                    in_tool_response,
                    "Missing {} before {} in formatted sample (question_id={}, node_id={})",
                    Self::TOOL_RESPONSE_START_TAG,
                    Self::TOOL_RESPONSE_END_TAG,
                    formatted_sample.question_id,
                    formatted_sample.node_id
                );
                in_tool_response = false;
            }

            cursor = tag_pos + tag.len();
        }

        assert!(
            !in_response,
            "Formatted sample must close {} (question_id={}, node_id={})",
            Self::RESPONSE_END_TAG,
            formatted_sample.question_id,
            formatted_sample.node_id
        );
        assert!(
            !in_tool_response,
            "Formatted sample must close {} (question_id={}, node_id={})",
            Self::TOOL_RESPONSE_END_TAG,
            formatted_sample.question_id,
            formatted_sample.node_id
        );
        assert_eq!(
            cleaned.len(),
            byte_modes.len(),
            "Byte-mode map must align with cleaned content"
        );

        let encoding = tokenizer
            .encode(cleaned, false)
            .unwrap_or_else(|err| {
                panic!(
                    "Failed to tokenize sample (question_id={}, node_id={}): {}",
                    formatted_sample.question_id, formatted_sample.node_id, err
                )
            });
        let input_ids: Vec<i32> = encoding
            .get_ids()
            .iter()
            .map(|id| {
                assert!(*id <= i32::MAX as u32, "Token id must fit in i32");
                *id as i32
            })
            .collect();
        assert!(!input_ids.is_empty(), "Tokenized input must be non-empty");
        let offsets = encoding.get_offsets();
        assert_eq!(
            offsets.len(),
            input_ids.len(),
            "Tokenizer offsets length must match input_ids length"
        );

        let mut labels: Vec<i32> = Vec::with_capacity(input_ids.len());
        let mut previous_mode: Option<ByteMode> = None;
        for (token_index, (start, end)) in offsets.iter().enumerate() {
            if *end <= *start {
                labels.push(Self::IGNORE_LABEL);
                previous_mode = None;
                continue;
            }
            assert!(
                *start < byte_modes.len(),
                "Token start offset out of bounds (start={}, len={})",
                start,
                byte_modes.len()
            );
            let mode = byte_modes[*start];
            let label = match mode {
                ByteMode::OutsideResponse => Self::IGNORE_LABEL,
                ByteMode::InResponse => input_ids[token_index],
                ByteMode::InToolResponse => {
                    if previous_mode != Some(ByteMode::InToolResponse) {
                        end_of_conversation_id
                    } else {
                        Self::IGNORE_LABEL
                    }
                }
            };
            labels.push(label);
            previous_mode = Some(mode);
        }

        assert_eq!(labels.len(), input_ids.len(), "labels must align with input_ids");

        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        enum Region {
            OutsideResponse,
            InResponse,
            InToolResponse,
        }

        let mut reconstructed = String::new();
        let mut region = Region::OutsideResponse;
        let mut segment_start = 0usize;

        let decode_segment = |start: usize, end: usize| -> String {
            if start >= end {
                return String::new();
            }
            let ids_u32: Vec<u32> = input_ids[start..end]
                .iter()
                .map(|id| {
                    assert!(*id >= 0, "Token id must be non-negative");
                    *id as u32
                })
                .collect();
            tokenizer.decode(&ids_u32, false).unwrap_or_else(|err| {
                panic!(
                    "Failed to decode token segment (question_id={}, node_id={}, start={}, end={}): {}",
                    formatted_sample.question_id,
                    formatted_sample.node_id,
                    start,
                    end,
                    err
                )
            })
        };

        for token_index in 1..=labels.len() {
            let boundary = token_index == labels.len() || labels[token_index] != labels[token_index - 1];
            if !boundary {
                continue;
            }

            reconstructed.push_str(&decode_segment(segment_start, token_index));

            let ended_label = labels[token_index - 1];
            let next_label = if token_index < labels.len() {
                Some(labels[token_index])
            } else {
                None
            };

            if region == Region::OutsideResponse
                && ended_label == Self::IGNORE_LABEL
                && next_label.is_some_and(|label| label != Self::IGNORE_LABEL)
            {
                reconstructed.push_str(Self::RESPONSE_START_TAG);
                region = Region::InResponse;
            } else if region == Region::InResponse
                && ended_label != Self::IGNORE_LABEL
                && next_label == Some(Self::IGNORE_LABEL)
            {
                if ended_label == end_of_conversation_id {
                    if token_index == labels.len() {
                        reconstructed.push_str(Self::RESPONSE_END_TAG);
                        region = Region::OutsideResponse;
                    } else {
                        reconstructed.push_str(Self::TOOL_RESPONSE_START_TAG);
                        region = Region::InToolResponse;
                    }
                } else {
                    reconstructed.push_str(Self::RESPONSE_END_TAG);
                    region = Region::OutsideResponse;
                }
            } else if region == Region::InToolResponse
                && ended_label == Self::IGNORE_LABEL
                && next_label.is_some_and(|label| label != Self::IGNORE_LABEL)
            {
                reconstructed.push_str(Self::TOOL_RESPONSE_END_TAG);
                region = Region::InResponse;
            }

            segment_start = token_index;
        }

        assert_eq!(
            region,
            Region::OutsideResponse,
            "Reconstruction must end outside response (question_id={}, node_id={})",
            formatted_sample.question_id,
            formatted_sample.node_id
        );

        let reconstructed_ids: Vec<i32> = tokenizer
            .encode(reconstructed.clone(), false)
            .unwrap_or_else(|err| {
                panic!(
                    "Failed to re-tokenize reconstructed sample (question_id={}, node_id={}): {}",
                    formatted_sample.question_id,
                    formatted_sample.node_id,
                    err
                )
            })
            .get_ids()
            .iter()
            .map(|id| {
                assert!(*id <= i32::MAX as u32, "Token id must fit in i32");
                *id as i32
            })
            .collect();
        assert_eq!(
            reconstructed_ids,
            input_ids,
            "Reconstructed content must be unambiguous from input_ids and labels"
        );

        TrainingSampleTokenized {
            question_id: formatted_sample.question_id,
            node_id: formatted_sample.node_id,
            input_ids,
            labels,
            reconstructed,
            input_length: encoding.get_ids().len(),
            advantage: formatted_sample.advantage,
        }
    }

    pub fn formatted_to_tokenized(
        &self,
        formatted_sample: &TrainingSampleFormatted,
    ) -> TrainingSampleTokenized {
        let tokenizer = self.load_tokenizer();
        self.formatted_to_tokenized_with_tokenizer(formatted_sample, &tokenizer)
    }

    pub fn generate_tokenized_samples(
        &self,
        formatted_samples: &[TrainingSampleFormatted],
    ) -> Vec<TrainingSampleTokenized> {
        let tokenizer = self.load_tokenizer();
        formatted_samples
            .iter()
            .map(|sample| self.formatted_to_tokenized_with_tokenizer(sample, &tokenizer))
            .collect()
    }
}

// use the same style as AssetFileAdvantageComposition
impl AssetFile for AssetFileTrainingTokenized {
    type FileModel = Vec<TrainingSampleTokenized>;

    fn fetch(&self) -> Self::FileModel {
        self.synchronize();
        read_json_lines(self.file_path()).unwrap()
    }

    fn synchronize(&self) -> crate::version_tracking::Base64Hash {
        let asset_file_training_formatted = AssetFileTrainingFormatted {
            model: self.model,
            dataset: self.dataset.clone(),
            num_samples: self.num_samples,
            hyperparameters: self.hyperparameters.clone(),
        };
        let formatted_hash = asset_file_training_formatted.synchronize();

        let tracking_content = match read_json::<AssetFileTrainingTokenizedTracking>(
            self.version_tracking_path(),
        ) {
            Ok(mut tracking) => {
                if tracking.formatted_hash != formatted_hash
                    || tracking.tokenized_schema_version != Self::TOKENIZED_SCHEMA_VERSION
                {
                    let formatted_samples = asset_file_training_formatted.fetch();
                    let tokenized_samples = self.generate_tokenized_samples(&formatted_samples);
                    write_jsonl_file(self.file_path(), &tokenized_samples).unwrap_or_else(|err| {
                        panic!(
                            "Failed to write tokenized training set output to {}: {}",
                            self.file_path(),
                            err
                        )
                    });
                    tracking.formatted_hash = formatted_hash.clone();
                    tracking.tokenized_schema_version = Self::TOKENIZED_SCHEMA_VERSION;
                }
                tracking
            }
            Err(_) => {
                let formatted_samples = asset_file_training_formatted.fetch();
                let tokenized_samples = self.generate_tokenized_samples(&formatted_samples);
                write_jsonl_file(self.file_path(), &tokenized_samples).unwrap_or_else(|err| {
                    panic!(
                        "Failed to write tokenized training set output to {}: {}",
                        self.file_path(),
                        err
                    )
                });
                AssetFileTrainingTokenizedTracking {
                    formatted_hash,
                    tokenized_schema_version: Self::TOKENIZED_SCHEMA_VERSION,
                }
            }
        };
        write_json(self.version_tracking_path(), &tracking_content).unwrap();
        hash_file(self.file_path()).unwrap()
    }
}
