[project]
name = "credit-assignment-sglang"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    # "torch",
    # "transformers",
    # "kernels",
    "sglang",
]

[tool.uv]
environments = ["sys_platform == 'linux'"]
prerelease = "allow"

# [[tool.uv.index]]
# name = "pytorch-cu126"
# url = "https://download.pytorch.org/whl/cu126"
# explicit = true

# [tool.uv.sources]
# torch = { index = "pytorch-cu126" }
