training_plan = "lora_current"
advantage_clip = 3.0
learning_rate = 1e-05
weight_decay = 0.01
grad_accum_steps = 128
log_time_interval = 30
checkpoint_save_time_interval = 300
seed = 42
# lora specific
lora_rank = 64
lora_alpha = 128
lora_dropout = 0.05
lora_target_modules_csv = "q_proj,k_proj,v_proj,o_proj"
resume_checkpoint_tag = "auto"
