[project]
name = "credit-assignment-common"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "datasets>=4.8.5",
    "python-dotenv>=1.0.0",
    "research-utility",
    "torch",
    "transformers>=4.46.0",
    "accelerate>=0.34.0",
    "matplotlib>=3.10.9",
    "peft>=0.19.1",
    "flash-attn>=2.6.3; sys_platform == 'linux'",
    # used for LLM python tool calling
    "sympy>=1.14.0",
    "numpy>=2.4.6",
    "scipy>=1.17.1",
    "numexpr>=2.14.1",
    "flash-linear-attention>=0.5.0",
    "causal-conv1d>=1.6.2.post1",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
research-utility = { path = "../../../research-utility", editable = true }

[tool.uv]
environments = ["sys_platform == 'linux'"]
prerelease = "allow"

[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]
