cargo run --bin bin_orchestrator -- \
    --model-cli-name llama-3.1-8b-instruct \
    --max-rollout-concurrency 300 \
    --config-nickname grpo \
    --validation-rollout-config-path config/rollout_config_validation_tool.json \
    --training-rollout-config-path config/rollout_config_training_grpo.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 20 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 3 \
    --advantage-calculation-policy tree-mappo-posterior \
    --training-config-common-path config/training/common.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --num-python-tool-servers 1 \
    --sglang-server-log-path logs/sglang_server_llama31_grpo.txt \
    --message-log-path logs/messages_llama31_grpo.txt \
    --num-gpus 1 \
    --ui true
