cargo run --bin bin_orchestrator -- \
    --model-cli-name llama-3.1-8b-instruct \
    --max-rollout-concurrency 300 \
    --config-nickname grpo_notool \
    --validation-rollout-config-path config/rollout_config_validation_notool.json \
    --training-rollout-config-path config/rollout_config_training_grpo_notool.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 10 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 5 \
    --advantage-calculation-policy tree-mappo-posterior \
    --training-config-common-path config/training/common_ddp.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --max-python-processes 4 \
    --num-gpus 1 \
    --storage-large-files-dir "/volume/large_files" \
    --storage-medium-files-dir "/volume/medium_files" \
    --storage-small-files-dir "/volume/small_files" \
    --keep-action-logs true \
    --ui true
