cargo run --bin bin_orchestrator -- \
    --model-cli-name mistral-7b-instruct-v0.3 \
    --max-rollout-concurrency 300 \
    --config-nickname grpo_notool \
    --validation-rollout-config-path config/rollout_config_validation_notool.json \
    --training-rollout-config-path config/rollout_config_training_grpo_notool.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 100 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 5 \
    --advantage-calculation-policy tree-mappo-posterior \
    --training-config-common-path config/training/common.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --max-python-processes 1 \
    --inference-wrapper-log-path logs/inference_wrapper_mistral_grpo_notool.txt \
    --training-wrapper-log-path logs/training_wrapper_mistral_grpo_notool.txt \
    --tui-log-path logs/mistral-7b-instruct-v0.3_grpo_notool.bin \
    --num-gpus 1 \
    --storage-large-files-dir "$PWD" \
    --storage-small-files-dir "$PWD" \
    --ui true
