cargo run --bin bin_orchestrator -- \
    --model-cli-name qwen3-4b \
    --max-rollout-concurrency 300 \
    --config-nickname std \
    --validation-rollout-config-path config/rollout_config_validation_tool.json \
    --training-rollout-config-path config/rollout_config_training_std.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 10 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 3 \
    --advantage-calculation-policy tree-mappo-posterior \
    --training-config-common-path config/training/common_ddp.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --max-python-processes 4 \
    --num-gpus 1 \
    --mount-dir "/volume" \
    --keep-action-logs true \
    --ui true
