cargo run --bin bin_orchestrator -- \
    --model-cli-name qwen2.5-7b \
    --max-rollout-concurrency 300 \
    --config-nickname branch8_fsdp \
    --validation-rollout-config-path config/rollout_config_validation_tool.json \
    --training-rollout-config-path config/rollout_config_training_branch8.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 100 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 5 \
    --advantage-calculation-policy tree-mappo-posterior \
    --training-config-common-path config/training/common_fsdp.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --max-python-processes 1 \
    --sglang-server-log-path logs/sglang_server_qwen25_branch8_fsdp.txt \
    --tui-log-path logs/qwen2.5-7b_branch8_fsdp.bin \
    --num-gpus 4 \
    --ui true
