cargo run --bin bin_orchestrator -- \
    --model-cli-name qwen2.5-7b \
    --max-rollout-concurrency 300 \
    --config-nickname treerpo \
    --validation-rollout-config-path config/rollout_config_validation_tool.json \
    --training-rollout-config-path config/rollout_config_training_treerpo.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 100 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 5 \
    --advantage-calculation-policy tree-rpo-win-rate \
    --training-config-common-path config/training/common.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --max-python-processes 1 \
    --inference-wrapper-log-path logs/inference_wrapper_qwen25_treerpo.txt \
    --training-wrapper-log-path logs/training_wrapper_qwen25_treerpo.txt \
    --tui-log-path logs/qwen2.5-7b_treerpo.bin \
    --num-gpus 1 \
    --storage-large-files-dir "$PWD" \
    --storage-small-files-dir "$PWD" \
    --ui true
