cargo run --bin bin_orchestrator -- \
    --model-cli-name qwen3-4b \
    --max-rollout-concurrency 300 \
    --config-nickname std_fsdp \
    --validation-rollout-config-path config/rollout_config_validation_tool.json \
    --training-rollout-config-path config/rollout_config_training_std.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 20 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 5 \
    --advantage-calculation-policy tree-mappo-posterior \
    --training-config-common-path config/training/common_fsdp.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --num-python-tool-servers 1 \
    --sglang-server-log-path logs/sglang_server_qwen34_fsdp.txt \
    --message-log-path logs/messages_qwen34_fsdp.txt \
    --tui-server-port 7878 \
    --num-gpus 4 \
    --ui true
