cargo run --bin bin_orchestrator -- \
    --model-cli-name qwen2.5-7b \
    --max-rollout-concurrency 300 \
    --config-nickname branch32 \
    --validation-rollout-config-path config/rollout_config_validation_tool.json \
    --training-rollout-config-path config/rollout_config_training_branch32.json \
    --posterior-hyperparameters-path config/posterior_hyperparameters.json \
    --num-total-epochs 100 \
    --cumulative-avg-abs-advantage-cutoff 0.5 \
    --num-iterations-limit 5 \
    --advantage-calculation-policy tree-mappo-posterior \
    --training-config-common-path config/training/common.toml \
    --training-time 600 \
    --training-rollout-time-limit-secs 600 \
    --validation-rollout-time-limit-secs 1200 \
    --num-python-tool-servers 1 \
    --sglang-server-log-path logs/sglang_server_qwen25_branch32.txt \
    --tui-log-path logs/branch32.bin \
    --num-gpus 1 \
    --ui true
