# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vllm_wrapper.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vllm_wrapper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vllm_wrapper.proto\x12\x0fvllm_wrapper.v1\"\x1d\n\x08TokenIds\x12\x11\n\ttoken_ids\x18\x01 \x03(\x05\"V\n\nVllmPrompt\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12.\n\ttoken_ids\x18\x02 \x01(\x0b\x32\x19.vllm_wrapper.v1.TokenIdsH\x00\x42\x08\n\x06prompt\"\xc4\x01\n\x0bVllmRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12+\n\x06prompt\x18\x02 \x01(\x0b\x32\x1b.vllm_wrapper.v1.VllmPrompt\x12\x12\n\nmax_tokens\x18\x03 \x01(\r\x12\"\n\x1ainclude_stop_str_in_output\x18\x04 \x01(\x08\x12\x19\n\x11requires_logprobs\x18\x05 \x01(\x08\x12\x0c\n\x04stop\x18\x06 \x03(\t\x12\x13\n\x0btemperature\x18\x07 \x01(\x02\"0\n\x0bVllmLogprob\x12\x10\n\x08token_id\x18\x01 \x01(\x05\x12\x0f\n\x07logprob\x18\x02 \x01(\x02\"?\n\x0bTopLogprobs\x12\x30\n\ncandidates\x18\x01 \x03(\x0b\x32\x1c.vllm_wrapper.v1.VllmLogprob\"j\n\x0cVllmLogprobs\x12\x0e\n\x06tokens\x18\x01 \x03(\x05\x12\x16\n\x0etoken_logprobs\x18\x02 \x03(\x02\x12\x32\n\x0ctop_logprobs\x18\x03 \x03(\x0b\x32\x1c.vllm_wrapper.v1.TopLogprobs\"U\n\x0bVllmSuccess\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12/\n\x08logprobs\x18\x02 \x01(\x0b\x32\x1d.vllm_wrapper.v1.VllmLogprobs\"\"\n\tVllmError\x12\x15\n\rerror_message\x18\x01 \x01(\t\"x\n\x0cVllmResponse\x12/\n\x07success\x18\x01 \x01(\x0b\x32\x1c.vllm_wrapper.v1.VllmSuccessH\x00\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1a.vllm_wrapper.v1.VllmErrorH\x00\x42\n\n\x08response2V\n\x0bVllmWrapper\x12G\n\x08Generate\x12\x1c.vllm_wrapper.v1.VllmRequest\x1a\x1d.vllm_wrapper.v1.VllmResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vllm_wrapper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENIDS']._serialized_start=39
  _globals['_TOKENIDS']._serialized_end=68
  _globals['_VLLMPROMPT']._serialized_start=70
  _globals['_VLLMPROMPT']._serialized_end=156
  _globals['_VLLMREQUEST']._serialized_start=159
  _globals['_VLLMREQUEST']._serialized_end=355
  _globals['_VLLMLOGPROB']._serialized_start=357
  _globals['_VLLMLOGPROB']._serialized_end=405
  _globals['_TOPLOGPROBS']._serialized_start=407
  _globals['_TOPLOGPROBS']._serialized_end=470
  _globals['_VLLMLOGPROBS']._serialized_start=472
  _globals['_VLLMLOGPROBS']._serialized_end=578
  _globals['_VLLMSUCCESS']._serialized_start=580
  _globals['_VLLMSUCCESS']._serialized_end=665
  _globals['_VLLMERROR']._serialized_start=667
  _globals['_VLLMERROR']._serialized_end=701
  _globals['_VLLMRESPONSE']._serialized_start=703
  _globals['_VLLMRESPONSE']._serialized_end=823
  _globals['_VLLMWRAPPER']._serialized_start=825
  _globals['_VLLMWRAPPER']._serialized_end=911
# @@protoc_insertion_point(module_scope)
